# Generated by Django 5.2.4 on 2025-09-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serconn_app', '0004_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='provider_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='seeker_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
