# Generated by Django 5.2.4 on 2025-09-03 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serconn_app', '0005_servicerequest_provider_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='rates',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
