# Generated by Django 5.2.4 on 2025-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serconn_app', '0006_remove_serviceprovider_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='provider_profiles/'),
        ),
    ]
