# Generated by Django 5.2.4 on 2025-09-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serconn_app', '0007_serviceprovider_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
