# Generated by Django 5.2.4 on 2025-09-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serconn_app', '0008_serviceprovider_first_name_serviceprovider_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='services_offered',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
