# Generated by Django 5.0.6 on 2025-08-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serconn_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceprovider",
            name="user",
            field=models.TextField(),
        ),
    ]
